### ISSUE TITLE
Android - W/AHBottomNavigation: The items list should have at least 3 items

### ISSUE THREAD

**Issue by adamski** [wix/react-native-navigation#176]
I'm getting this error in my app which precedes a NullPointerException as I assume the items array is empty. 
```java
W/AHBottomNavigation: The items list should have at least 3 items
```
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.clearColorFilter()' on a null object reference
                                                                             at com.aurelhubert.ahbottomnavigation.AHHelper.getTintDrawable(AHHelper.java:37)
                                                                             at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createClassicItems(AHBottomNavigation.java:320)
                                                                             at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createItems(AHBottomNavigation.java:213)
                                                                             at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.addItem(AHBottomNavigation.java:750)
                                                                             at com.reactnativenavigation.activities.BottomTabActivity.setTabsWithIcons(BottomTabActivity.java:297)
```

The examples don't have this issue. I'm in the process of porting a working iOS app using RNN over to Android. I'm wondering if there are any differences in the API that I might have missed? Looking at the examples the API seems (almost?) identical across platforms.

**Comment by guyca** [comment]
Hey @adamski, I think you've described two different issues.
The first is simply a warning since you have less then three tabs. According the Android design guidelines, Bottom navigation shouldn't be used with less then three tabs. We plan to add an option to start an app with `TabLayout` in the `AppBar` as the main form of navigation. That will provide a solution to this use case since tabs can be used with 2 tabs.
In version 2.0 which will be released in 1-2 weeks, there will be an option to add top tabs to a screen, so you could start a single screen app which has tabs.

Regarding the error, do you have bottom tabs with out icons?

**Comment by adamski** [comment]
I see them as related, as I have 3 tabs, but for some reason it seems that `items` is empty. Been trying to track it down but difficult to debug as I can't put debug log statements in the AHBottomNavigation lib as its read only.

**Comment by guyca** [comment]
Check if some of the icons have `.ios` suffix - the packager ignores these files by default when you run on Android.
This error is in debug or release mode? Are you debugging on emulator or a device?

**Comment by adamski** [comment]
@guyca I'm debugging on emulator via Android Studio, pretty sure its in debug mode (I'm just hitting Run from AS). The icons are the same ones from the example app, so no they don't have the `ios` suffix.

**Comment by adamski** [comment]
In my app, `screen.icon` within `SetupTabsTask.Map` is e.g. `reactcomponents_images_one` - which reflects the folder structure of the image, i.e `ReactComponents/Images/one@2x.png`.
However `screen.getIcon(this.mActivity)` returns `null`.

**Comment by guyca** [comment]
@adamski I'm not sure I understand what values you're getting.
Can you please add a log [right before the icons are loaded](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/activities/BottomTabActivity.java#L265), and print the value of `screen.icon`

```java
if (screen.icon != null) {
    Log.d("TEST, "icon: " + screen.icon);
    icons.put(screen, screen.getIcon(this.mActivity));
}
```

You're supposed to get the icon's uri
```
icon: http://10.0.2.2:8081/assets/img/one@2x.png?platform=android&hash=dae2cd284683782f52cc954c01a43f41
icon: http://10.0.2.2:8081/assets/img/two@2x.png?platform=android&hash=dae2cd284683782f52cc954c01a43f41
```

What RN version are you using?

**Comment by adamski** [comment]
RN version 0.28
`screen.icon` is `reactcomponents_images_one` (that's exactly where I had my log statement)- so looks like its not getting the URL, but a processed version of it instead.

**Comment by guyca** [comment]
@adamski I tried running the example project with RN 0.28 - icons are loading fine.
How your tabs are defined? maybe there's something with the require statement.
What Android version are you using?

**Comment by adamski** [comment]
Android version on emulator is 6. I'll dig further in to see how the icons are loaded.

**Comment by adamski** [comment]
Tabs are defined as e.g.
```js
Navigation.startTabBasedApp({
          tabs: [
            {
              label: 'One',
              icon: require('../Images/one.png'),
              selectedIcon: require('../Images/one_selected.png'),
              title: 'One',
              screen: 'myApp.ScreenOne',
              navigatorStyle: navigatorStyle
            },

```

**Comment by adamski** [comment]
So I think I understand whats going on. I had issues getting the packager to serve JS on Android so I was saving the JS bundle. I was not doing the same for the image assets. The underscored path is actually the saved filename. Now that I'm saving the assets too, I can see the images in the `drawables` folder.  I am still getting the same error but at least I understand whats going on a bit better. 
The strange thing is I also did the same with the example project (saved the JS bundle to `assets`) but I didn't have this issue...

**Comment by adamski** [comment]
If I check for the icons in `startTabBasedActivity` with 
```java
for (int i=0; i<screens.size(); i++) {
    Log.d("RctActivityModule.startTabBasedApp","screen.icon = "+screens.getMap(i).getString("icon"));  
}
```
I can see the filenames without the suffix e.g. `screen.icon = reactcomponents_images_one`

However once it gets to the `doInBackground` method in `BottomTabActivity`, `screen.icon` appears to be `null`.

**Comment by guyca** [comment]
@adamski Can you try using `gradle` to build your app?

cd to `android` folder and use `./gradlew assembleDebug` or `./gradlew assembleRelease`
install the generated apk from `android/app/build/outputs/apk/`

**Comment by adamski** [comment]
@guyca I just built the apk and installed onto the emulator with `adb -e install -r app/build/outputs/apk/app-x86-debug.apk `. Unfortunately I got the same result as from the AndroidStudio build.

**Comment by adamski** [comment]
The plot thickens. I have spent the last couple of days doing lots of debugging on this. I've narrowed it down to what seems to be a very strange case of a disappearing `ReadableArray` object. 

As I described above, if I put the following debug code into `RctActivityModule.startTabBasedApp`
```java
            // Debug
            for (int i=0; i<screens.size(); i++) {
                Log.d("RctActivityModule.startTabBasedApp","screen.icon = "+screens.getMap(i).getString("icon"));
            }
```
I can see the icons. 

However, it seems that once it gets to the `createScreens` method the `ReadableArray screens` object becomes empty. If I add the following debug code to `createScreens`
```java
    private ArrayList<Screen> createScreens(ReadableArray screens) {

        ArrayList<Screen> ret = new ArrayList<>();
        for (int i = 0; i < screens.size(); i++) {
            Log.d("createScreens", "screens.getMap.icon = "+screens.getMap(i).getString("icon"));
            ret.add(new Screen(screens.getMap(i)));
            Log.d("createScreens", "screen.title = " + ret.get(i).title);
            Log.d("createScreens", "screen.icon = " + ret.get(i).icon);
        }
        return ret;
    }
```
I get an exception:
```
com.facebook.react.bridge.NoSuchKeyException: couldn't find key icon in dynamic object
```
And if I remove that `getMap` debug line I see `screen.title = null`.

This is very strange. I am wondering if there is something going on with threads here. My head hurts from trying to work this out. And the example app does not exhibit this behaviour.

**Comment by guyca** [comment]
@adamski I'm not sure the issue is disappearing object. If you're installing a debug version, the image assets aren't copied to the device, since they are not part of the apk you are installing. They are served from the local server. So if you're not getting a URL, the asset name doesn't help much.
It's a positive sign that the images are resolved but getting `reactcomponents_images_one` doesn't help us much for debug builds.

the following command seems suspicious to me `--assets-dest Builds/AndroidStudio/app/src/main/res/ `
Maybe the images are copied to device, You could try to [resolve the images in `IconUtils` by name](http://stackoverflow.com/questions/3042961/how-do-i-get-the-resource-id-of-an-image-if-i-know-its-name).

To be sure the images do indeed get bundled into the apk, try to pull the apk from emulator and unzip it. You can refer to [this SO](http://stackoverflow.com/questions/11012976/get-apk-of-installed-app) thread for examples how to do it.

If you can provide a sample project where this issue is reproduced I can debug it on my end as well.

**Comment by adamski** [comment]
@guyca the image thing is a red herring, as far as I see. The real issue that I can see here is that the `ReadableArray` object seems to become null in the `createScreens` method. `title` is also null. 

One difference I have noticed is in my app `build.gradle` I do not have a reference to `react.gradle`. I have copied it over but I think I need to convert it to the gradle experimental format (!) for it to work. Could this be related to the issue I'm seeing? 

I'll try and create a simple example project, thanks.

**Comment by adamski** [comment]
@guyca I've solved this issue now, still not sure what the hell was going on - trying to create an example project proved to me that it was not any issue with the JUCE exporter or RNN - the RNN example ran fine alongside JUCE JNI. I rebuilt the Android Studio project, deleted and reinstalled npm modules, and now I'm past that issue. Have a feeling it might have been due to some unintended modification to RNN while doing some debugging..

**Comment by guyca** [comment]
@adamski glad to hear!
