### ISSUE TITLE
View below the screen flickers in 0.50.1

### ISSUE THREAD

**Issue by lyyqqrr** [wix/react-native-navigation#2138]
### Issue Description
View at the bottom of the screen flickers in 0.50.1

Like One.js the followling,the text flickers.But it was OK in RN 0.47.

### Steps to Reproduce / Code Snippets / Screenshots
`export default class One extends Component {
    render() {
        return (
            <View style={{flex:1,flexDirection:"column-reverse"}}>
            <Text>OneOneOne</Text>
            </View>
        );
    }
}`

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: 0.50.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by mario-advancis** [comment]
Same issue on Android. Someone have an idea?

**Comment by salisuabubakar** [comment]
Am having the same issue. Please some issue on android. Please help. Thanks for your time

**Comment by enahum** [comment]
Same issue on Android for me

**Comment by johngoren** [comment]
I struggled with a flicker issue that went away when I rolled back to React Native 0.49.x. I suspect this falls under the category of Wix devoting their energies to RNNv2.0 instead of RNNv.1.0 (which I was using.)

**Comment by Flavien** [comment]
Also had the same problem. Had to revert to 0.49.

This bug currently makes the library unusable with React Native 0.50+.

**Comment by Flavien** [comment]
@guyca any idea what the issue could be?

**Comment by nromptea42** [comment]
I'm having the same issue on Android only.

**Comment by guyca** [comment]
@Flavien We're upgrading to RN 0.50+ in two weeks 🙏 - I'll have more information then.

**Comment by CherishIt** [comment]
Same problem for us. 
Are there any solutions or workarounds besides downgrading RN?

**Comment by DevAlien** [comment]
I think the only thing to do is waiting for the update to support RN 50+

**Comment by thechefchen** [comment]
Same here, I'm experiencing a lot of dropped frames after upgrading from 0.49.3 to 0.50.3. Sigh, not sure if this is related. Tried to work on workarounds but no luck.

**Comment by chaitanya0bhagvan** [comment]
React native 0.50 added a feature to support dynamically sized ReactRootView in android. This change is not working well with RNN. This change is causing the app to call onGlobalLayout repeatedly, which is causing flickering and dropped frames. You can notice that the CPU utilization of the app is quite high for any screen with a navbar or a bottom tab.

What I noticed is if I disabled navbar (navBarHidden = true) or enabled drawUnderNavBar the app does not rerender in a loop. I have not tested whether this works for BottomTabs.

**Comment by thechefchen** [comment]
Hi @chaitanya0bhagvan 

Thanks for your insight! The layout seems indeed re-rendering.

I logged around the render function and it's doing fine. So I guess it's a higher-level re-rendering happening repeatedly.

I turned on the profiling and the dropped frame # is going up crazy.

I tried both the navBarHidden = true and drawUnderNavBar = true on 0.50.3 but none of them is working for tabBasedNavBars from the bottom. 

In the end, I ended up downgrading to 0.49.3 and use react-native-safe-area-view to patch the iphonex case.

**Comment by korre** [comment]
I have the same issue. Downgrading from 0.50.0 to 0.49.0 does the trick for now.

**Comment by emin93** [comment]
Hi @thechefchen 

Thanks for your analysis. I can confirm that i have the same issues. In the end I also did the downgrade to RN 0.49.5, but the latest version of react-native-safe-area-view (0.2.0) has a hard dependency to RN 0.50. When I use the 0.1.0 version, the packager throws me an error that duplicate versions of RN are provided.

So for now, i'm kind of stuck 😞

**Comment by bitcrumb** [comment]
Same issue here. Downgrading fixed it as well.

Also, I experienced an extra issue as well. The content of my ScrollViews would suddenly flow underneath the tab bar. Adding `paddingBottom: 50` to `contentContainerStyle` moved the content up again so that it was visible. Note that the ScrollView itself would not "underlap" the tab bar, only the content view.

**Comment by DevAlien** [comment]
@guyca Hi, what's the progress to upgrade to RN 0.50? so I know if I have to downgrade now or if it is worth waiting. Thanks for the great job you all do.

**Comment by rh389** [comment]
To pin this down a bit, the issue was introduced by https://github.com/facebook/react-native/commit/4ca617211b23754ffecf23c1ddc8772bc32420f0#diff-bf3c3ea5966a54499984a9b64c8587a7

**Comment by rh389** [comment]
Since it looks like @guyca / wix [may not get to this issue for a while](https://github.com/wix/react-native-navigation/issues/2248#issuecomment-348112205) any short-term fix might have to come from the community (us!).

I think what might be happening here is that the when android does a first pass over the `RelativeLayout` containing, for example, a `TopBar` and a single-screen `ContentView`, the wrong height (the full screen height) is initially passed to `onMeasure` of the `ContentView`, which is in turn passed to the root react component. That's always happened, and previously it wasn't a problem because the second layout pass would always immediately call `onMeasure` again with the correct height.

Now though in RN 0.50, whenever the size of the JS-side root component is updated, it enqueues an update of the `ReactRootView` on a background thread. So the first pass will cause it to measure at the wrong/full screen height again, prompting another loop setting the wrong height, and the second pass will maintain a second loop setting the correct height.

That causes an infinite layout loop (with corresponding CPU use), with the react view flickering between the height it should be and the full height of its parent `ViewGroup`.

I'm hoping someone else can pitch in here with ideas on fixing that ;)

**Comment by SudoPlz** [comment]
@rh389 I bow to your excellence, how did you find out about all this?

**Comment by rh389** [comment]
@SudoPlz Thanks - I just grabbed a shovel and kept digging!

More specifically, I built against RN from source at various points in the android change history to pin it down to that one commit, and then spent the last few hours debugging with breakpoints and hacks. The problem is I'm really not an android guy and I'm not that familiar with how the layouts should ideally interact, what operations need to go on which threads, etc, in order to come up with a proper solution. I'll keep digging, but I'm mostly hoping this helps point someone who knows what they're doing in the right direction.

**Comment by chaitanya0bhagvan** [comment]
I have fixed this in my [fork](https://github.com/chaitanya0bhagvan/react-native-navigation). I will send a PR once I have tested all the screens. I would appreciate it if you guys could test it in your apps.

**Comment by chaitanya0bhagvan** [comment]
@rh389 you are correct about RelativeLayout and ContentView. 
A Screen has the following structure

```
<Screen>
<TopBar/>
<ContentView/>
</Screen>

```
ContentView is added to the Screen with LayoutParams(MATCH_PARENT, MATCH_PARENT) and another rule to place it below TopBar, in the first pass ContentView height is Screen height, in the second pass height is (Screen height - TopBar height). With rn 0.50 feature to dynamically measure the children, this causes another pass over the layout and the cycle continues. Here ContentView is behaving like it not pinned to the parent. The fix is to use LayoutParams(MATCH_PARENT, WRAP_CONTENT) and use RelativeLayout constraints to pin it to the parent bottom and below TopBar.

In BottomTabsLayout the Screen looks like this

```
<BottomTabsLayout>
<Screen/>
<BottomTab/>
</BottomTabsLayout>

```
Here the behaviour is similar but for some reason, it is not respecting RelativeLayout constraint to place the Screen above the BottomTab. So the solution was to override onMeasure and measure each child and calculate the layout height, if the layout height is greater than the height of the children then it means the children are yet to be measured. Once the children height and layout height are equal can stop the measuring process.

**Comment by mattmcdonald-uk** [comment]
@chaitanya0bhagvan Thanks for your work looking at this!

Im experiencing the issue described in #2144 where I can't reach the end of scroll views. 

It sounds like that would share a common root cause with this issue, but I've applied your patch and it's still an issue. Do you have any ideas why that might be?

**Comment by chaitanya0bhagvan** [comment]
@mattmcdonald-uk I looked at your issue but I am not able to reproduce it. I added a comment there please take a look.

**Comment by enahum** [comment]
@chaitanya0bhagvan your fork is working great for me, are you going to submit a PR?

**Comment by mattmcdonald-uk** [comment]
@chaitanya0bhagvan I don't, but you're right I must now have something else going on causing the issue.

I did a quick test of a new app with a single `ScrollView`. Pre-your patch it exhibits the behaviour in #2144. Post-your patch it works perfectly!

**Comment by kurtsergey** [comment]
@chaitanya0bhagvan fork works for me also.

**Comment by enahum** [comment]
Have anyone done test with the fork on RN < 0.50?

**Comment by chaitanya0bhagvan** [comment]
@enahum @kurtsergey @mattmcdonald-uk It does not work with BottomTabs with drawer. Once I fix this I will send a PR.

**Comment by thechefchen** [comment]
@chaitanya0bhagvan Thanks for your work! Would it suppose to work with bottomtabs WITHOUT drawer on Android? Please let me know. I'll test with 0.50 + your folk on native navigation if you need. ^^

**Comment by chrismllr** [comment]
@chaitanya0bhagvan Thanks for the work. We are running into the issue with a `navBarHidden: true` and bottom Tab app. Currently testing your fork to see how it works, will report back!

**Comment by chaitanya0bhagvan** [comment]
I have issued a [PR](https://github.com/wix/react-native-navigation/pull/2261) for this fix. Read the PR description for a complete explanation of the issue and the fix. 
For folks who are testing my initial fix, you will notice that I have discarded all those changes.
This fix is also backward compatible.

**Comment by alimek** [comment]
@chaitanya0bhagvan just checked your commit from your fork. Works for me even on `0.51.0`. Cool! :) Thanks mate

**Comment by chaitanya0bhagvan** [comment]
@alimek You are welcome!

**Comment by eduplus** [comment]
Confirmed to fix the issue on RN 0.50.4, can we get this merged?

**Comment by maphongba008** [comment]
It works for me on RN 0.50.3, thanks @chaitanya0bhagvan

**Comment by leoi11** [comment]
https://github.com/wix/react-native-navigation/pull/2261#issuecomment-351430303
> Looks like this fix was released with version 1.1.307. 🙌🏼

**Comment by celso-henrique** [comment]
The problem still happening when using tabs on Android :(

**Comment by JoseIgnacio92** [comment]
It keeps happening to me, the behavior is as if the View rises and falls and repeats indefinitely.

Try the latest version of ReactNative, also version 0.50.1 and the latest version of the navigator.

Check the class that was modified and has the adjustment, but it still happens

**Comment by pribeh** [comment]
Still happening over here with the latest version of RN and v1 of RNN

**Comment by blairvanderhoof** [comment]
@chaitanya0bhagvan It seems your fix made the flicker go away, but it also prevents the keyboard from pushing up inputs in a ScrollView. Now inputs that are farther down in a ScrollView get covered by the keyboard.  Here is the resulting bug https://github.com/wix/react-native-navigation/issues/3424

I narrowed down that changing back to this code fixed the issue. Any ideas?

ContentView.java
```
  @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
        int measuredHeight = viewMeasurer.getMeasuredHeight(heightMeasureSpec);
        setMeasuredDimension(viewMeasurer.getMeasuredWidth(widthMeasureSpec), measuredHeight);
    }

```

**Comment by biomancer** [comment]
It seems like the issue is back in React Native 0.60 (it was working fine in 0.58.6) - using navbar causes endless layout recalculations, hiding it fixes things. This is probably related to one of lasted changes of these https://github.com/facebook/react-native/commits/0.60-stable/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java,
most probably https://github.com/facebook/react-native/commit/e75843516770cdc41ba02941af0264a036eb60e8#diff-a04970ddd4a6df34e2245d37f78486e3 and/or https://github.com/facebook/react-native/commit/2e42cc76521ba5bf3692e806eef2d3e64d5ffa1a#diff-a04970ddd4a6df34e2245d37f78486e3,
as these changes seem to be directly related to explanations above. 
@chaitanya-bhagavan could you maybe take a look on these changes? Any hints to how to fix it for RNN v1 would help so much!

**Comment by chaitanya-bhagavan** [comment]
@biomancer I am not using this library for sometime. I have moved on to
flutter
