### ISSUE TITLE
[v2] Remote Debugging

### ISSUE THREAD

**Issue by frankenthumbs** [wix/react-native-navigation#2481]
### Issue Description

Hey y'all,

Does anybody have remote debugging working on V2? i can't get it working on the playground app nor in my own repo.

---
### Environment
* React Native Navigation version: latest v2 repo
* React Native version: 0.49.5
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): (Simulator 11.2) / (Emulator Nexus 5x API 25)

**Comment by redwind** [comment]
Did you install debug success ?

**Comment by frankenthumbs** [comment]
@redwind not sure what you mean.

**Comment by frankenthumbs** [comment]
did more digging around in the PRs.. it looks like this patch by @joonhocho fixes this on ios! https://github.com/wix/react-native-navigation/pull/1816/files

still looking at android

**Comment by guyca** [comment]
cc @gran33

**Comment by yogevbd** [comment]
Fixed in #1816

**Comment by ujwal-setlur** [comment]
I am getting this as soon as I add a second screen to a stack.

**Comment by ujwal-setlur** [comment]
Any update on this?

**Comment by d-olivas** [comment]
I'm still having this issue with android "Could not connect to development server", iOS works fine. We're currently using react-native v0.59.3, react v16.8.6 and react-native-navigation v2.16.0. Also, when I run it in android it doesn't run the packager server and if there is one already running it doesn't connect to it.
