### ISSUE TITLE
[v2] Modal screenBackgroundColor transparent bug

### ISSUE THREAD

**Issue by yusufyildirim** [wix/react-native-navigation#3272]
### Issue Description
Hi,

I need a modal with transparent background. I set my modal's background to transparent but there is a bug I think. It comes transparent but turns to white.
### Steps to Reproduce / Code Snippets / Screenshots
Here is the gif:
![2018-05-29 18 59 59](https://user-images.githubusercontent.com/22980987/40670676-86d7f668-6372-11e8-83f2-a319cb66f623.gif)

---
### Environment
* React Native Navigation version: v2@alpha
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): iOS (Didn't test android)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
When a modal is displayed, the previous controller is removed from hierarchy. If you'd to display a transparent Modal over the previous controller, you need to add `modalPresentationStyle: 'overCurrentContext' option to you modal.

**Comment by yusufyildirim** [comment]
I tried it before you said but nothing happened. I tried again and still same.

**Comment by guyca** [comment]
Interesting. can you include some code snippets?

**Comment by yusufyildirim** [comment]
Sure. This my my code for testing purpose. I just realized, this might be about stack i don't know. I'm gonna try without stack.

```
const tagModal = {
        stack: {
          children: [{
            component: {
              name: 'TagModal',
              passProps: { tag, onSuccess: this.onTagAdded },
              options: {
                screenBackgroundColor: 'transparent',
                modalPresentationStyle: 'overCurrentContext',
                topBar: {
                  visible: false,
                  animate: true,
                },
              },
            },
          }],
        },
      };
  
      navigation.showModal(tagModal);
```

**Comment by yusufyildirim** [comment]
Yupp this is about stack. Working well without stack layout. I mean, like this:

```
const tagModal = {
        component: {
          name: 'TagModal',
          passProps: { tag, onSuccess: this.onTagAdded },
          options: {
            screenBackgroundColor: 'transparent',
            modalPresentationStyle: 'overCurrentContext',
            topBar: {
              visible: false,
              animate: true,
            },
          },
        },
      };
  
      navigation.showModal(tagModal);
```

**Comment by guyca** [comment]
You added `modalPresentationStyle` to the wrong node. You need to add it to the root component presented in the modal, which in your case is the stack.

**Comment by yusufyildirim** [comment]
Yea I realized and tried it too but nothing changed :D

**Comment by yusufyildirim** [comment]
I even tried Navigation.setDefaultOptions({ modalPresentationStyle: 'overCurrentContext' }); 😂

**Comment by spencewine** [comment]
I'm having a similar issue, except worse in some cases. The modal is neither transparent when setting it to transparent nor covering the appropriate portion of the screen (I'm trying to get it to do anything but cover the entire screen. I've tried `overCurrentContext`, `pageSheet`, `formSheet`, `popOver`, and `currentContext` and they all end-up being fullscreen. My set-up is this: I have a checkout that holds the cart summary and an address form for step one of the checkout process.
```
<ScrollView>
    <CartSummaryContainer/>
    <AddressFormContainer/>
</ScrollView>
```
I've made the ScrollView's background color red to help myself visualize element placement. The 
 `AddressFromContainer` has a method for showing a modal upon touching the country or region/state inputs. Here is my modal method: 
```
    togglePicker(picker){
        console.log('picker', picker);
        const { navbarIcon } = this.state;
        const { countryValue, regionValue } = this.props;
        const showCountry = picker === 'showCountry';
        const name = showCountry ? 'native.CountryPicker' : 'native.RegionPicker';
        Navigation.showModal({
            stack: {
                children: [{
                    component: {
                        name,
                        passProps: {
                            picker,
                            onChange: showCountry ? this.countryChange : this.regionChange,
                            value: showCountry ? countryValue : regionValue,
                            showDefaultOption: !!showCountry,
                            defaultOptionLabel: showCountry ? 'United States' || countryValue : null,

                        },

                    },
                }],
                options: {
                    topBar: {
                        buttonColor: 'black',
                        leftButtons: [
                            {
                                id: 'close',
                                icon: navbarIcon,
                            },
                        ],

                    },
                },
                screenBackgroundColor: 'transparent',
                modalPresentationStyle: 'formSheet',
            },

        });
    }
```
Any idea why I'm always getting fullscreen regardless of the modalPresentationStyle and why the background is not transparent?

**Comment by dorthwein** [comment]
this is still a bug

**Comment by muhammadsr** [comment]
Having the same issue here :(

**Comment by fabianunger** [comment]
Same over here. Is there any update on that issue?

**Comment by fabianunger** [comment]
Works fine without stack!

like so:
`  Navigation.showModal({
      component: {
        name: 'LighboxSpareCard',
        options: {
          screenBackgroundColor: 'transparent',
          modalPresentationStyle: 'overCurrentContext',
          topBar: {
            visible: false,
            animate: true,
          },
        },
      },
    });`

**Comment by fabianunger** [comment]
@dorthwein @muhammadsr Have you tried it without stack?

**Comment by fabianunger** [comment]
@muhammadsr Which Versions / Platform do you use? Maybe you want to share some more code? Is EDIT_DB_MODAL a string?

**Comment by muhammadsr** [comment]
```
react-native": "0.57.0",
"react": "16.5.1",
"react-native-navigation": "^2.0.2582",
```

Device info: Using the iOS iPhone X Simulator and my iPhone X phone to test this


> @muhammadsr Which Versions / Platform do you use? Maybe you want to share some more code? Is EDIT_DB_MODAL a string?
Yes `EDIT_DB_MODAL` is just a string.

**Comment by Aleksion** [comment]
I'm hitting the same issue :( Doesn't work whether or not I do it with stack.

```typescript
 Navigation.events().registerAppLaunchedListener(() => {
    Navigation.setDefaultOptions({
      topBar: {
        visible: false,
      },
    })
    Navigation.setRoot({
      root: {
        stack: {
          children: [
            {
              component: {
                name: defaultScreen,
              },
            },
          ],
        },
      },
    })
  })
```

```typescript
// MyScreen.tsx

...
	onGoToReservation = () => {
		Navigation.showModal({
			component: {
				name: MAP_SCREENS.searchFilter,
				options: {
					screenBackgroundColor: "transparent",
					modalPresentationStyle: "overCurrentContext",
					topBar: {
						visible: false,
						animate: true,
					},
				} as any,
			},
		})
	}
...


```

**Comment by muhammadsr** [comment]
I created a PR that addresses the issue for non stack modal 
https://github.com/wix/react-native-navigation/pull/4159

**Comment by yogevbd** [comment]
Fixed in latest version

**Comment by muhammadsr** [comment]
It's not fixed in version `2.0.2608` 
![ezgif-4-06893c14de9e](https://user-images.githubusercontent.com/1937488/47270396-0dae5a00-d520-11e8-87eb-f405e6d25caa.gif)

**Comment by muhammadsr** [comment]
I confirm the fix

**Comment by skumarcm** [comment]
I am still facing the issue on iOS. It is working on android

**Comment by Olovorr** [comment]
Unfortunately as @skumarcm said, it doesn't seem to work on iOS 🙁

**Comment by kevinvangelder** [comment]
@Olovorr  @skumarcm I was also still having this issue, but then I found this comment and it worked for me. https://github.com/wix/react-native-navigation/issues/4134#issuecomment-430277278

It seems that `screenBackgroundColor` is ignored and instead we should be using `layout: { backgroundColor: 'transparent' }`

**Comment by skumarcm** [comment]
> @Olovorr @skumarcm I was also still having this issue, but then I found this comment and it worked for me. [#4134 (comment)](https://github.com/wix/react-native-navigation/issues/4134#issuecomment-430277278)
> 
> It seems that `screenBackgroundColor` is ignored and instead we should be using `layout: { backgroundColor: 'transparent' }`

Awesome!! That works.
Thanks!!!

**Comment by sturmenta** [comment]
```
export const showModal = async props => {
  await Navigation.showModal({
    component: {
      name: 'modal', // screen name - previous registered
      passProps: props,
      options: {
        layout: { backgroundColor: 'transparent' },
        screenBackgroundColor: 'transparent',
        modalPresentationStyle: 'overCurrentContext',
        topBar: {
          visible: false,
          drawBehind: true,
        },
      },
    },
  });
};
```

`"react-native-navigation": "^2.13.1"`
