### ISSUE TITLE
[v2] Build failed with Android Studio 3.1.2

### ISSUE THREAD

**Issue by hkurokawa** [wix/react-native-navigation#3419]
### Issue Description
Build failed with the below error when running `react-native run-android` after setup described [here](https://wix.github.io/react-native-navigation/v2/#/docs/Installing)

```bash
$ react-native run-android
Scanning folders for symlinks in /home/hiroshi/workspaces/android/SampleRNApp/node_modules (33ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Starting a Gradle Daemon, 1 incompatible and 8 stopped Daemons could not be reused, use --status for details

> Configure project :app 
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..

> Configure project :react-native-navigation 
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..
downloadRobolectricDependencies into /home/hiroshi/workspaces/android/SampleRNApp/android/build/robolectric-3.5.1-dependencies

> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
D8: Program type already present: android.support.design.widget.CoordinatorLayout$Behavior

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /home/hiroshi/workspaces/android/SampleRNApp/android/app/build/intermediates/transforms/dexBuilder/debug/21.jar, /home/hiroshi/workspaces/android/SampleRNApp/android/app/build/intermediates/transforms/dexBuilder/debug/22.jar, ...

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### Steps to Reproduce / Code Snippets / Screenshots
1. Install react-native-navigation following the guide: https://wix.github.io/react-native-navigation/v2/#/docs/Installing
2. Run `react-native run-android`

Here is my build.gradle, app/build.gradle, settings.gradle

**build.gradle**

```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
  repositories {
    google()
    mavenCentral()
    mavenLocal()
    jcenter()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:3.1.3'

    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
  }
}

allprojects {
  repositories {
    google()
    mavenCentral()
    mavenLocal()
    jcenter()
    maven {
      // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
      url "$rootDir/../node_modules/react-native/android"
    }
  }
}

ext {
  compileSdkVersion = 27
  targetSdkVersion = 27
  minSdkVersion = 19
  buildToolsVersion = "27.0.3"
  supportLibVersion = "27.1.1"
  googlePlayServicesVersion = "11.8.0"
  androidMapsUtilsVersion = "0.5+"
}
```

**app/build.gradle**

```gradle
apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [entryFile: "index.js"]

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = false
def enableProguardInReleaseBuilds = false

android {
  compileSdkVersion rootProject.ext.compileSdkVersion
  buildToolsVersion rootProject.ext.buildToolsVersion

  defaultConfig {
    applicationId "com.hkurokawa.samplernapp"
    minSdkVersion rootProject.ext.minSdkVersion
    targetSdkVersion rootProject.ext.targetSdkVersion
    missingDimensionStrategy "RNN.reactNativeVersion", "reactNative55"
    versionCode 1
    versionName "1.0"
    ndk {
      abiFilters "armeabi-v7a", "x86"
    }
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
  splits {
    abi {
      reset()
      enable enableSeparateBuildPerCPUArchitecture
      universalApk false // If true, also generate a universal APK
      include "armeabi-v7a", "x86"
    }
  }
  buildTypes {
    release {
      minifyEnabled enableProguardInReleaseBuilds
      proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
    }
  }
  // applicationVariants are e.g. debug, release
  applicationVariants.all { variant ->
    variant.outputs.each { output ->
      // For each separate APK per architecture, set a unique version code as described here:
      // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
      def versionCodes = ["armeabi-v7a": 1, "x86": 2]
      def abi = output.getFilter(OutputFile.ABI)
      if (abi != null) {
        // null for the universal-debug, universal-release variants
        output.versionCodeOverride = versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
      }
    }
  }
}

dependencies {
  implementation fileTree(dir: "libs", include: ["*.jar"])
  implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
  implementation "com.facebook.react:react-native:0.55.4" // From node_modules
  implementation project(':react-native-navigation')
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
  from configurations.compile
  into 'libs'
}
```

**settings.gradle**

```gradle
rootProject.name = 'SampleRNApp'

include ':app'
include ':react-native-navigation'
project(':react-native-navigation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-navigation/lib/android/app')
```

---
### Environment
* React Native Navigation version: 2.0.2373
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Android 8.1, Debug

---
### Remarks
The problem was solved by the below change.  It seems a lower version of support library causes this issue (See https://stackoverflow.com/questions/49112190/error-program-type-already-present-android-support-design-widget-coordinatorl ).

```diff
--- /home/hiroshi/temp/build.gradle     2018-06-22 18:57:43.984886562 +0900
+++ ./node_modules/react-native-navigation/lib/android/app/build.gradle  2018-06-22 18:23:17.236358407 +0900
@@ -66,9 +66,9 @@
 
 dependencies {
     implementation fileTree(include: ['*.jar'], dir: 'libs')
-    implementation 'com.android.support:design:26.1.0'
-    implementation 'com.android.support:appcompat-v7:26.1.0'
-    implementation 'com.android.support:support-v4:26.1.0'
+    implementation "com.android.support:design:${rootProject.ext.supportLibVersion}"
+    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
+    implementation "com.android.support:support-v4:${rootProject.ext.supportLibVersion}"
     implementation 'com.aurelhubert:ahbottomnavigation:2.1.0'
     implementation 'com.github.clans:fab:1.6.4'
 
@@ -81,4 +81,4 @@
     testImplementation 'org.assertj:assertj-core:3.8.0'
     testImplementation 'com.squareup.assertj:assertj-android:1.1.1'
     testImplementation 'org.mockito:mockito-core:2.13.0'
-}
\ No newline at end of file
+}
```

**Comment by jinshin1013** [comment]
I also get lots of warning about the third party libraries using lower or different version of dependencies. But I never faced an build failed issue because of this.

**Comment by guyca** [comment]
@hkurokawa You can force whichever version of the support packages you need using [resolutionStrategy](https://wix.github.io/react-native-navigation/v2/#/docs/Installing?id=_9-force-the-same-support-library-version-across-all-dependencies)

**Comment by hkurokawa** [comment]
Hi Guy,

Thank you.  I somehow overlooked that part.  Fixed now!  :+1:

**Comment by ilovett** [comment]
Thanks!

**Comment by vleals** [comment]
@hkurokawa , I'm new to react and having the same issue. What did you have to add to resolutionStrategy? thanks!

**Comment by vivekshah-zymr** [comment]
@hkurokawa, I am facing the exact same issue as you for android. (The project runs well on iOS simulator.)

I am using,
```
"react-native-navigation": "^1.1.487"
"react-native": "0.57.1"
```

**Exception while running on Android**
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
```

**android/build.gradle**
```
android {
     compileSdkVersion 25
     buildToolsVersion "25.0.1"
     ...
 }

 dependencies {
     compile fileTree(dir: "libs", include: ["*.jar"])
     compile "com.android.support:appcompat-v7:23.0.1"
     compile "com.facebook.react:react-native:+"
     compile project(':react-native-navigation')
 }

```
And I have followed all the steps which described in [this documentation.](https://wix.github.io/react-native-navigation/#/installation-android) But still gets the error.

Even I tried to change **android/build.gradle** file with below code. But get the same error.
```
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion '28.0.2'
}
```
Can anyone please look into this and help me out? Thank you in advance!

**Comment by ighotouch** [comment]
If you make the above changes and still no hope, ensure you have your `supportLibVersion = "28.0.0"` version updated to match the version supported by your buildTool
