### ISSUE TITLE
Duplicated render of componentDidMount and the render method

### ISSUE THREAD

**Issue by hiradarshadi** [wix/react-native-navigation#3472]
### Issue Description

Whether in a single screen app or a tabbased one, when you for example log something in componentDidMount or the render method, it logs twice.

### Steps to Reproduce / Code Snippets / Screenshots

<img width="384" alt="screen shot 2018-07-02 at 12 14 36 am" src="https://user-images.githubusercontent.com/29271309/42138083-ffd3ac68-7d8c-11e8-917a-bc844041d0cd.png">
<img width="931" alt="screen shot 2018-07-02 at 12 16 04 am" src="https://user-images.githubusercontent.com/29271309/42138105-4546a44e-7d8d-11e8-9660-a2d1f18ac453.png">

Note that I'm using one file for each of my tab pages. so it logs 4 times 👎 
```
        Navigation.setRoot({
            root: {
                bottomTabs: {
                    children: [{
                        stack: {
                            children: [{
                                component: {
                                    name: 'Sign',
                                }
                            }],
                            options: {
                                bottomTab: {
                                    title: 'Tab 1',
                                    icon: require('./assets/images/my-offers.png'),
                                    testID: 'FIRST_TAB_BAR_BUTTON'
                                }
                            }
                        }
                    },
                    {
                        component: {
                            name: 'Sign',
                            passProps: {
                                text: 'This is tab 2'
                            },
                            options: {
                                bottomTab: {
                                    title: 'Tab 2',
                                    icon: require('./assets/images/my-shop.png'),
                                    testID: 'SECOND_TAB_BAR_BUTTON'
                                }
                            }
                        }
                    }]
                }
            }
        });
```

---
### Environment
* React Native Navigation version: 2.0.2381
* React Native version: 0.51.0
* Platform(s): Both
* Device info: Samsung Galaxy S7, Android 7 (also IPhone 6s)

**Comment by mammad2c** [comment]
Same +1

**Comment by guyca** [comment]
Hey @hiradarshadi Can you reproduce this in the playground app?

**Comment by mammad2c** [comment]
hi @guyca , I have this issue on playground app. add the following code in /src/screens/WelcomeScreen.js at render methor :

```
render() {
       ...
       + console.log("calling twice");
       ...
}
```

also enabled 'Hot reloading' and 'Live reloading' after the changes. after reloading 3 or 2 times, the console log throw 2 times. That means the component is rendering twice. 
![image](https://user-images.githubusercontent.com/16647736/42161220-52918c18-7e0f-11e8-84bd-2d80e94c7c99.png)

**Comment by guyca** [comment]
If I understood the issue correctly, it should be resolved by https://github.com/wix/react-native-navigation/pull/3487
Please checkout version

**Comment by mammad2c** [comment]
Hi again,
I checked this version and still not fixed

**Comment by guyca** [comment]
Hey, I just understood the actual issue. BottomTab screens are all mounted and rendered when the BottomTab is attached.
The motivation behind this is that you want the BottomTab child views to be mounted and rendered (ready) so when the selected tab changes - the screen is already rendered and there won't be any flickering or lags.

**Comment by mammad2c** [comment]
can you send me your code? I need componentDidMount per tabs. How did you fixed it?

**Comment by mammad2c** [comment]
hi @guyca , I still have this issue. How can I fix it? My app have 5 tabs like Instagram and need to call life-cycle methods per tabs.

**Comment by guyca** [comment]
Hey @mammad2c 
This isn't an issue and there's nothing to fix. All BottomTabs are mounted at the same time by design. If they weren't mounted at creation time and instead mounted when user first navigates to them - you would experience flickering as it might take a noticeable amount of time for the component to mount.

You probably want to handle you logic when the tab [first appears ](https://wix.github.io/react-native-navigation/v2/#/docs/events?id=componentdidappear).

**Comment by tonymontana100** [comment]
Free internet

qq

**Comment by mammad2c** [comment]
thank you @guyca :1st_place_medal: 
my problem get fixed :) :1st_place_medal:
