### ISSUE TITLE
How to disable landscape mode

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#349]
### Issue Description

Hi,

I tried this but not working. how to disable landscape on android.

```
<activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:launchMode="singleTop"
        android:screenOrientation="portrait"
        android:configChanges="keyboard|keyboardHidden|screenSize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
```
Thanks so much!
---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
Hey @agumack 
We've recently added `portraitOnlyMode` property to `startApp`.
```js
  Navigation.startSingleScreenApp({
    screen: {
      ...
    },
    animationType: 'slide-down',
    ...
    portraitOnlyMode: true
  });
```

**Comment by agumack** [comment]
thanks @guyca  (y)

**Comment by jaggerwang** [comment]
@guyca , `portraitOnlyMode` only working on Android? I tested it on iOS but it's not working.

My app has a video player page, and I want to only enable orientation in this page. I tried many ways, but still can not achieve the goal. Here is my way.

1. Turn on Landscape orientation in Xcode. If not turned on, all pages of app can not be rotated.
![image](https://cloud.githubusercontent.com/assets/1255011/22018415/b699ce8c-dce9-11e6-8a6c-8ab0acb54d4b.png)

2. Set `portraitOnlyMode` prop to true in `startSingleScreenApp` and `startTabBasedApp`. My app will check user login state in startSingleScreenApp and then enter into startTabBasedApp.

3. In the video player page, set orientation listener and lock to the orientation according to the received event. I'm using this [react-native-orientation](https://github.com/yamill/react-native-orientation) lib.
```javascript
  componentDidMount() {
    ...
    this.orientationListener = orientation => {
      let {setPlayerState} = this.props;
      if (orientation == 'LANDSCAPE-LEFT') {
        Orientation.lockToLandscapeLeft();
        setPlayerState({orientation: 'LANDSCAPE-LEFT'});
      } else if (orientation == 'LANDSCAPE-RIGHT') {
        Orientation.lockToLandscapeRight();
        setPlayerState({orientation: 'LANDSCAPE-RIGHT'});
      } else {
        Orientation.lockToPortrait();
        setPlayerState({orientation: 'PORTRAIT'});
      }
    };
    Orientation.addSpecificOrientationListener(this.orientationListener);
    Orientation.unlockAllOrientations();
  }

  componentWillUnmount() {
    Orientation.removeOrientationListener(this.orientationListener);
    Orientation.lockToPortrait();
  }
```

Am I doing in the right way?

**Comment by guyca** [comment]
`portraitOnlyMode` is only implemented on Android as of now. Unfortunately I'm not familiar with `Orientation`

**Comment by jaggerwang** [comment]
@guyca , that's ok. Thanks!

**Comment by eneskaya** [comment]
Does this also work on for `startTabBasedApp`? I inserted it like that:

```
Navigation.startTabBasedApp({
   tabs: [...],
   portraitOnlyMode: true
});
```
But unfortunately it doesn't work.

**Comment by guyca** [comment]
@eneskaya `portraitOnlyMode` is deprecated, use `orientation` instead.
https://wix.github.io/react-native-navigation/#/top-level-api - set in appStyle to lock orientation for the entire app.
https://wix.github.io/react-native-navigation/#/styling-the-navigator - use in navigatorStyle to apply orientation to a specific modal

**Comment by eneskaya** [comment]
Thanks! Must've missed it in the docs 😅

**Comment by rf1804** [comment]
@guyca in startTabBasedApp it's working but in startSingleScreenApp it's not

> react-native: 0.51.0
> react-native-navigation: 1.1.309

I want my complete app to be in portrait only.
I've implemented it like this: 
```
Navigation.startSingleScreenApp({
              screen: {
                screen : 'home',
                navigatorStyle: {
                  orientation: 'portrait'
                }
              }
            });
```

**Comment by AnnShabanova** [comment]
The same problem as @rf1804

**Comment by henricazottes** [comment]
Solution: 
```javascript
await Navigation.startSingleScreenApp({
  screen: {...},
  appStyle: {
    orientation: 'portrait'
  }
});
```

**Comment by luskin** [comment]
I am still receiving this problem, and I believe I have tried everything. I cannot get the app to stay in portrait mode when rotated. My manifest looks like this:

```
        <activity
            android:name="com.reactnativenavigation.controllers.NavigationActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:screenOrientation="portrait"
            android:launchMode="singleTop"
            android:windowSoftInputMode="stateAlwaysHidden|adjustPan|adjustResize"
            android:theme="@style/AppTheme"
            />
```

and my Navigation setup is as follows:

```
export const launchOnboarding =() => {
  Navigation.startSingleScreenApp({
    screen: {
      screen: Screens.Onboarding,
      navigatorStyle: {
        navBarHidden: true
      },
      navigatorButtons: {}
    },
    animationType: 'fade',
    appStyle: {
      orientation: 'portrait'
    },
  })
}
```

Anybody have any advice? Our app gets totally busted when rotated!

**Comment by Orlandohub** [comment]
@luskin not sure if this will help but this is my implementation and it worked after everything else failed:
```
     Navigation.startSingleScreenApp({
      screen: {
        screen: 'tidy.Home',
        navigatorStyle: {
          navBarHidden: true,
          statusBarHideWithNavBar: false,
          statusBarColor: '#1AA5FD',
        },
      },
      appStyle: {
        orientation: 'portrait',
      },
      drawer: {
        left: {
          screen: 'tidy.NavigationDrawer',
          // fixedWidth: 400,
          passProps: {},
        },
        style: {
          leftDrawerWidth: 53,
        },
        disableOpenGesture: true,
        type: 'MMDrawer',
        animationType: 'slide-and-scale',
      },
    });
```
Not sure if by putting it immediately after the `screen` option helps...

**Comment by rk-gpguide** [comment]
Hi everyone ... 
I am having my app rebuilt in React Native ... 
- It is a Landscape-only design.
- In react native iOS I can turn the device, and use landscape on both sides.  Great !
- In react native Android, it seems to be locked on ONE side only !  This can be problematic.

Here is what my developer told me:
> The issue is that on Native Android app - a user can hold a tablet in both Landscape modes, but in React Native library it allows to have only one landscape mode

I have trouble believing this !!
Is this true ?
Is there a way to allow React Native Android to work on BOTH sides ?

Thanks.

**Comment by adam-aerobotics** [comment]
@rk-gpguide @osynligsebastian Setting `orientation: 'sensorLandscape'` should let the app rotate in both landscape and reverse landscape.

**Comment by rk-gpguide** [comment]
Hi @adam-aerobotics ,

Many thanks !!  Have passed your feedback and code to my developers for investigation.

R-

**Comment by osynligsebastian** [comment]
> Setting `orientation: 'sensorLandscape'` should let the app rotate in both landscape and reverse landscape.

This appears to allow all orientations except reverse portrait on android.

**Comment by linuxgg** [comment]
> @eneskaya `portraitOnlyMode` is deprecated, use `orientation` instead.
> 
> * https://wix.github.io/react-native-navigation/#/top-level-api - set in appStyle to lock orientation for the entire app.
> * https://wix.github.io/react-native-navigation/#/styling-the-navigator - use in navigatorStyle to apply orientation to a specific modal

doc are `404`

**Comment by linuxgg** [comment]
refer here:
https://wix.github.io/react-native-navigation/#/docs/options-migration?id=orientation

**Comment by HarshaKoshila** [comment]
### This work bro

**Add this into react Navigation** 
appStyle: {
      orientation: 'portrait'
    },

**Inside  AndroidManifest.xml** 
**Change**  android:configChanges="keyboard|keyboardHidden|orientation|screenSize"  **to** android:configChanges="keyboard|keyboardHidden|screenSize"

**and Add new line**
<activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        **android:screenOrientation="portrait"**
        android:configChanges="keyboard|keyboardHidden|screenSize"
        android:windowSoftInputMode="adjustResize">

**Comment by alienalien13** [comment]
There is an option:
```
layout: {
  orientation: ['portrait', 'landscape'] // An array of supported orientations
}
```

https://wix.github.io/react-native-navigation/#/docs/options-migration?id=orientation

**Comment by mths0x5f** [comment]
What I'am just curious about is why RNN affects the manifest ability to lock the orientation

**Comment by syedammar** [comment]
> Solution:
> 
> ```js
> await Navigation.startSingleScreenApp({
>   screen: {...},
>   appStyle: {
>     orientation: 'portrait'
>   }
> });
> ```

Working for me

**Comment by duenwaldd1** [comment]
https://github.com/yamill/react-native-orientation works for me
