### ISSUE TITLE
Multiple crashes android.view.View.onRestoreInstanceState RNN V1.1.474

### ISSUE THREAD

**Issue by ankero** [wix/react-native-navigation#4030]
### Issue Description

We are getting multiple crash notifications from our Android app affecting multiple users & different phones & Android version. This therefore seems to be a wide issue. We are unable to replicate this issue as it seems to be related to app moving to sleep in background.

**Issue happens when app is in the background and is resumed from clicking a push notification.**

Crash logs indicate that the app never initialises, i.e. we never get any crash logs that indicate that the RNN app has initialised on push notification click. So could this relate to the @override in the MainApplication.java code snippet that prevents Android backpress from deleting the current activity?

### Steps to Reproduce / Code Snippets / Screenshots

Our index file that creates the app has the following in Android startup:
```
Navigation.isAppLaunched()
      .then(appLaunched => {
        if (appLaunched) {
          app.initApp(root);
        }

        new NativeEventsReceiver().appLaunched(a => {
          // Check initial notification before navigation app is started
          // This is because the RNN conflicts with the firebase messaging
          saveInitialNotification();

          // Check the logged in again here, since user may have
          // logged in or out in the meantime...
          app.hasLoggedInBefore().then(hasLoggedIn => {
            console.log(":::: hasLoggedBefore ::::", hasLoggedIn);
            setActivityResumed(hasLoggedIn);
            let root = hasLoggedIn ? "loggedInApp" : "login";
            app.startApp(root);
          });
        });
      })
```

MainApplication.java has this:

```
// When closing app in Android (i.e. backpressing), this prevents the app
    // from closing completely so users can resume their activities.
    // https://github.com/wix/react-native-navigation/issues/1022#issuecomment-329432373
    @Override
    public boolean clearHostOnActivityDestroy(Activity activity) {
         return false; 
    }
```

Stacktrace:

```
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.ourApp.ourApp/com.reactnativenavigation.controllers.NavigationActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.os.Bundle instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/0x1. Make sure other views do not use the same id.
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2957)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3032)
android.app.ActivityThread.-wrap11 (Unknown Source)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1696)
android.os.Handler.dispatchMessage (Handler.java:105)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:6944)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
```

```
Caused by java.lang.IllegalArgumentException
Wrong state class, expecting View State but received class android.os.Bundle instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/0x1. Make sure other views do not use the same id.
android.view.View.onRestoreInstanceState (View.java:18909)
android.view.View.dispatchRestoreInstanceState (View.java:18884)
android.view.ViewGroup.dispatchRestoreInstanceState (ViewGroup.java:3930)
android.view.ViewGroup.dispatchRestoreInstanceState (ViewGroup.java:3936)
android.view.ViewGroup.dispatchRestoreInstanceState (ViewGroup.java:3936)
android.view.ViewGroup.dispatchRestoreInstanceState (ViewGroup.java:3936)
android.view.ViewGroup.dispatchRestoreInstanceState (ViewGroup.java:3936)
android.view.ViewGroup.dispatchRestoreInstanceState (ViewGroup.java:3936)
android.view.View.restoreHierarchyState (View.java:18862)
com.android.internal.policy.PhoneWindow.restoreHierarchyState (PhoneWindow.java:2248)
android.app.Activity.onRestoreInstanceState (Activity.java:1153)
android.app.Activity.performRestoreInstanceState (Activity.java:1108)
android.app.Instrumentation.callActivityOnRestoreInstanceState (Instrumentation.java:1266)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2930)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3032)
android.app.ActivityThread.-wrap11 (Unknown Source)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1696)
android.os.Handler.dispatchMessage (Handler.java:105)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:6944)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
```

---
### Environment
* React Native Navigation version: 1.1.474
* React Native version: 0.53.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Release

**Comment by ankero** [comment]
Update on this issue, we removed this line from MainApplication.java to check if it was the thing causing the crashes. Unfortunately same issue still continues. So 

MainApplication.java removed code:

```
// When closing app in Android (i.e. backpressing), this prevents the app
    // from closing completely so users can resume their activities.
    // https://github.com/wix/react-native-navigation/issues/1022#issuecomment-329432373
    @Override
    public boolean clearHostOnActivityDestroy(Activity activity) {
         return false; 
    }
```

Next we are checking what's the result of removing this from MainActivity.java and can we even do that without breaking the app.

```
// Related to splash screen hang-up & notification click initialising
    // react-native-navigation again, resulting in errors.
    // https://github.com/wix/react-native-navigation/issues/2682
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        if (!isTaskRoot()) {
            finish();
            return;
        }
    }
```

**Comment by rawrmaan** [comment]
@ankero I believe this is fixed in #3688. Have a look and consider updating your `react-native-navigation` version to `npm i react-native-navigation@github:BasitAli/react-native-navigation#52ae13ed48a089828813b0c742be244fbf6c8b82` until that PR is merged.

**Comment by ankero** [comment]
Thanks @rawrmaan for the input. I'll update to the newest version to see what's the effect. 

@guyca please don't close this issue before it has been resolved. I can confirm that my efforts had no effect on fixing the issue, so we'll need to check if updating to newest version will do the trick. Don't worry, I'll report here when the issue is fixed and the Crashalytics reports show green.

**Comment by joshuapinter** [comment]
Hey guys, just to confirm, this only applies to Version 1 of the library, correct?

**Comment by ankero** [comment]
@joshuapinter I don't know. We started to move to v2, but it has so many bugs still and immediately showed instability so we decided to move away from RNN to React Navigation.

**Comment by joshuapinter** [comment]
@ankero Thanks for the reply. I think we’ll stick with React Navigation for now as well. We figured out how to persist the navigation state between Activity death.

**Comment by vjtc0n** [comment]
@ankero @joshuapinter Hello, do you discover any more about this issue?
For the statistics in firebase, with 1000 users, we have faced around 15-20 events of this crash.
It's really difficult to figure out because we don't have any devices crashes with this bug.
Maybe the firebase just throws the event but the real user doesn't face the crash?
None of my customer claim that the app crashed, we just see it in the firebase dashboard crashlytics.
Btw, we fixed a lot of issues in RNN v1, so we cannot move to v2/v3 right now, it's too much risk!
This issue is the only one left :D

**Comment by ankero** [comment]
Unfortunately not, we moved away from RNN to React Navigation. It took us about 3 weeks to complete the move. Well worth it since we can now support wider range of functionality including the share-to -functionality which doesn't work with RNN.

So my recommendation is to drop RNN.

**Comment by joshuapinter** [comment]
I concur with @ankero. Best bet is to stick with React Navigation.

**Comment by howg0924** [comment]
@vjtc0n Did you find any solution about this issue in the end?

We also encountered many random crashes in onRestoreInstanceState().

After searching on the Internet, it seems few developers encountered this issue. Is it possible there is something wrong in our RNN setup or some special functionality combination / code sequence triggered this?
