### ISSUE TITLE
custom title image component not being shown on IOS but works on Android 

### ISSUE THREAD

**Issue by AbanoubNassem** [wix/react-native-navigation#4165]
### Issue Description

custom Tobar->title (image component) not being shown on IOS but works on Android 

### Steps to Reproduce / Code Snippets / Screenshots

```
const Logo = ({ style }: any) => (
  <Image
    style={[styles.image, style]}
    resizeMode="contain"
    source={Theme.images.SplashLogo}
  />
);

const styles = StyleSheet.create({
  image: {
    flex: 1,
    alignSelf: "center"
  }
});

export default Logo;
```
then register it : 

`Navigation.registerComponent("Logo", () => Logo);`

after that setDefaultOptions :

 ```
 Navigation.setDefaultOptions({
    topBar: {
      visible: true,
      animate: true,
      drawBehind: false,
      title: {
        component: {
          name: "Logo",
          alignment: "center"
        }
      }
    }
  });
``` 

it shows up on Android , but not on the IOS simulator 
---
### Environment
* React Native Navigation version: ^2.0.2597
* React Native version: 0.57.3
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Debug

**Comment by yogevbd** [comment]
Fixed here: aa4326d

**Comment by AbanoubNassem** [comment]
@yogevbd 
it's not being fixed , the issue still exist!

**Comment by kirtishjain9** [comment]
@yogevbd/@guyca 

I'm having the same issue. Is it resolved permanently or not?

**Comment by emilioheinz** [comment]
Still not solved i think #5716 is related.

@guyca any solution?
