### ISSUE TITLE
Set to default type=MMdrawer animationType=slide

### ISSUE THREAD

**Issue by folivi** [wix/react-native-navigation#49]
Hi all,
anyone has figured out how to get rid of this message when opening sidemenu?
Cheers

**Comment by gran33** [comment]
Hi @folivi (and @madvas),
This warning msg is there just to let u know, that the default values has been set.
If u would like to disappear the waning, simple set values.

To keep the default values, set it to:
```
type="MMDrawer"
animationType="slide"
```

**Comment by folivi** [comment]
thanks for the reply, but in case of a TabBasedApp where to set those values?
thx again

**Comment by gran33** [comment]
@folivi I pushed a change, so u can now remove the warn and set (for the default drawer animation type):
inside your 
```
Navigation.startTabBasedApp({
...
  drawer: {
  type="MMDrawer"
  animationType="slide"
  ...
  }
})
```
U can have many animation types (took from [react-native-controllers](https://github.com/wix/react-native-controllers#drawercontrollerios)):
> if type=MMDrawer animationTypes=door/parallax/slide/slide-and-scale. If type=TheSideBar animationType=airbnb/facebook/luvocracy/wunder-list (Default is type=MMDrawer animationType=slide)

**Comment by folivi** [comment]
Great! 
Thanks a lot.
```

  drawer: {
      type: 'MMDrawer',
      animationType: 'slide',
      left: {
          screen: 'gsb.MenuView'
      }
  }

```

**Comment by gran33** [comment]
👍

**Comment by SvetoslavKuzmanov** [comment]
Hi all,

I'm still getting this warning and I cannot change the neither animation type nor the drawer type. Here is how I'm using it: 
```
Navigation.startSingleScreenApp({
    screen: {
      screen: 'example.WelcomeScreen',
      title: 'Welcome',
      navigatorStyle: {},
      navigatorButtons: {
        leftButtons: [{
          icon: iconsMap['ios-menu'],
          id: 'menu'
        }]
      }
    },
    drawer: {
      left: {
        screen: 'example.SideMenu'
      },
      type: 'MMDrawer',
      animationType: 'slide',
      disableOpenGesture: true
    },
  });
```

Any ideas anybody?

**Comment by jackread** [comment]
Doesn't look like this was implemented for startSingleScreenApp

Still getting a warning every time.

**Comment by gazpachu** [comment]
I'm also still getting that warning with startSingleScreenApp all the time.

**Comment by joshwhatk** [comment]
Same here. It may have something to do with the react-native version? I'm using version 0.30.0.

**Comment by folivi** [comment]
@joshwhatk @gazpachu 
your drawer should look something like this:

drawer: {
         type: 'MMDrawer',
         animationType: 'slide',
         left: {
             screen: 'viewNamespace.SideMenuView'
         },
     }
Note that the package doesn't follow RN version changes. I had to downgrade to RN 26 to get the package fully working
