### ISSUE TITLE
 Navigation.setDefaultOptions  Does NOT work on V3.1.0!

### ISSUE THREAD

**Issue by mrxrinc** [wix/react-native-navigation#5395]
### Issue Description

Just create a fresh project RN0.60.5 &  RNN 3.1.0, the  Navigation.setDefaultOptions does not work!. actually Im about to never again use RNN in future projects! :(

---
### Environment
* React Native Navigation version: 3.1.0
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iphone 8

**Comment by Damar95** [comment]
I'm using it in V3.
Did you set it before calling setRoot, as described in the docs?
https://wix.github.io/react-native-navigation/#/docs/styling?id=enabling-persistent-styling-properties

**Comment by pontusab** [comment]
It works in 3.0 but not in 3.1.

**Comment by mrxrinc** [comment]
@Damar95 yes I did everything I could imagine! but there is no result!

**Comment by mrxrinc** [comment]
@guyca Please help!

**Comment by TylerNRobertson** [comment]
@mrxrinc Agreed it doesn't work. Downgrade to v3.0.0 for it to be resolve temporarily.

**Comment by guyca** [comment]
@mrxrinc Are all options you set don't work? Or is it a specific option?

**Comment by Damar95** [comment]
Seems like its a iOS only bug. 3.1.0 works for me on android.

```js
Navigation.setDefaultOptions({
            layout: {
                // componentBackgroundColor: 'lightgray',
                direction: 'ltr',
            },
            statusBar: {
                visible: true,
                style: 'dark',
                backgroundColor: 'rgb(85, 128, 0)', 
            },
            topBar: {
                visible: true,
                background: {
                    color: 'rgb(85, 128, 0)',
                },
            },
            bottomTabs: {
                style: 'dark',
                textColor: 'rgb(0, 0, 0)',
                backgroundColor: 'rgb(85, 128, 0)',
            },
            bottomTab: {
                iconColor: 'rgb(50, 50, 50)',
                textColor: 'rgb(50, 50, 50)',
                selectedIconColor: 'rgb(0, 0, 0)',
                selectedTextColor: 'rgb(0, 0, 0)',
            },
            // backgroundImage: require('./../assets/img/background.jpg')
        });
```

**Comment by mrxrinc** [comment]
@guyca 
```
Navigation.setDefaultOptions({
    topBar: {
      visible: false,
      drawBehind: true
    },
    layout: {
      orientation: ['portrait'],
      backgroundColor: '#32434C'
    },
    statusBar: {
      blur: true,
      drawBehind: true,
      backgroundColor: '#00000011',
      style: 'light'
    }
  })
```

**Comment by OmgDef** [comment]
Having the same problem on iOS. 3.0 works fine, but 3.1 doesn't

**Comment by AbanoubNassem** [comment]
same issue here it's not working on ios `ver: 3.1`

**Comment by guyca** [comment]
Sorry for the trouble guys. I'm on this. Unfortunately the e2e which should have caught this bug was bugged as well 😕 
I should have a fix by tomorrow, you can use 3.0.0 until then, thanks for your patience 👍

**Comment by guyca** [comment]
Alright, fixed in 3.1.1. Please let me know if there any more issues regarding defaultOptions

**Comment by mrxrinc** [comment]
@guyca Thanks in advance. should I update it with 
```
npm install --save react-native-navigation@3.1.1
```

**Comment by tiagomelilo** [comment]
For me, v3.1.1. not solve my problem. =(
Any idea??

**Comment by Sharipkanov** [comment]
For ios everything works fine v3.1.1. But on android 
bottomTabs {visible: false, drawBehind: true} in setDefaultOptions doesn't work need to add option in each screen to work it correctly
P/s (sorry for my English)

**Comment by mrxrinc** [comment]
@guyca Still doesn't work! tried 'npm install --save react-native-navigation@3.1.1' also 'pod install'.
None is working!

**Comment by terreb** [comment]
@mrxrinc, try `cd ios && pod update`. If still not working:

```bash
rm -rf ios/build
rm -rf ~/Library/Developer/Xcode/DerivedData
rm -rf lib
watchman watch-del-all
rm -rf node_modules
rm -rf $TMPDIR/npm-*
rm -rf $TMPDIR/haste-*
rm -rf $TMPDIR/metro-*
rm -rf $TMPDIR/haste-map-react-native-packager-*
npm install
``` 

then `cd ios && pod update`

**Comment by vnshgrg** [comment]
I have 3.2.0 installed and can't change the statusBar style.

**Comment by rvera** [comment]
Same, I'm on 3.2.0 and this can't change the `statusBar` style either

**Comment by luskin** [comment]
I'm on `3.2.0` as well and `statusBar` remains unaffected

**Comment by jamesjara** [comment]
this library has bugs on any thing that you want to do. there is a test folder for nothing, so yep, I guess I can't delivery this task to my client without another bash hack script, so bad.

**Comment by guyca** [comment]
@jamesjara What options exactly don't work for you?

**Comment by paulosborne** [comment]
> this library has bugs on any thing that you want to do. there is a test folder for nothing, so yep, I guess I can't delivery this task to my client without another bash hack script, so bad.

@jamesjara 

If you have a problem, be specific and contribute to trying to solve the problem. I understand it's frustrating when something doesn't work, but the delivery of _your_ task to _your_ client is _your_ issue and it's success or failure are the direct result of the choices _you_ have made - don't go blaming everyone else.

Good luck :)

**Comment by jamesjara** [comment]
@paulosborne GitHub and GitHub issues are not about life and choices, it's about code, your statement doesn't have anything to do with it either, nor an even a solution to the problem (yes the bug!). waste of time your reply. 

To contribute a little bit with the thread, update your version to the latest one, create one single function to handle the creation of the Wix configuration object. remember to add Id's to the custom components  (this will save a lot of issues),  my  2 cents
