### ISSUE TITLE
React Native 0.73 `npx rnn-link` doesn't work 

### ISSUE THREAD

**Issue by retyui** [wix/react-native-navigation#7821]
### What happened?

starting from rn73 `*.java` files was convened to `*.kt`
so auto-linking doesn't work properly 

```bash
npx rnn-link

/tmp/Rn73/node_modules/react-native-navigation/autolink/postlink/path.js:10
exports.rootGradle = mainApplicationJava.replace(/android\/app\/.*\.java/, 'android/build.gradle');
                                         ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.<anonymous> (/Users/davydnarbutovich/tmp/Rn73/node_modules/react-native-navigation/autolink/postlink/path.js:10:42)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/davydnarbutovich/tmp/Rn73/node_modules/react-native-navigation/autolink/postlink/applicationLinker.js:2:12)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)


```

### What was the expected behaviour?

no js error, `*.kt` files supported out of the box 

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### In what environment did this happen?

React Native Navigation version: 7.37.2
React Native version: 0.73
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: 18
Device model: 
Android version:

**Comment by jtich** [comment]
+1

**Comment by JailsonSmidi** [comment]
Mesmo problema

**Comment by HaNguyenRN** [comment]
+1

**Comment by jtich** [comment]
The issue is that the following [line in path.js](https://github.com/wix/react-native-navigation/blob/6e7e8f61d4826b79a898a10adc49c72eb1a98b02/autolink/postlink/path.js#L8) assumes that `mainApplication` has the `java` extension, however it's now a kotlin file, which is why `mainApplicationJava` is undefined.

I was able to get around this issue by changing this line...
```javascript
var mainApplicationJava = glob.sync('**/MainApplication.java', ignoreFolders)[0];
```

to the following:
```javascript
var mainApplicationJava = glob.sync('**/MainApplication.{java,kt}', ignoreFolders)[0];
```

This way the glob.sync func matches either file extension.

**Comment by elmalakomar** [comment]
+1

**Comment by ArianHamdi** [comment]
Same here

**Comment by harunisik** [comment]
+1

**Comment by pramahaditamaputra** [comment]
is this issue has been solved ?

**Comment by stephanepericat** [comment]
i still have this issue as well

**Comment by d4vidi** [comment]
All, please track https://github.com/wix/react-native-navigation/issues/7834 for the official RN73 support 🙏🏻

**Comment by Eoinr2661** [comment]
Hi, I am also having this issue still, the above implementation from jtich made some of the auto-linking work, but still not fully.

**Comment by brifiction** [comment]
Hey guys, FYI the similar bug is back / regressed, apologies for appending to this issue. Note, I am using `yarn` = `4.4.0` and working on the React Native `0.74.5` project. Please take a look and apply a new patch when able 🙏 

And I tried using `npx rnn-link` and script failed, same error as original poster.

**Error output in terminal**
```bash
/private/var/www/rndemoapp0745/node_modules/react-native-navigation/autolink/postlink/path.js:10
exports.rootGradle = mainApplicationJava.replace(/android\/app\/.*\.java/, 'android/build.gradle');
```

**Dependency versions installed (with `yarn`)**
```json
"dependencies": {
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.5",
    "react-native-navigation": "^7.40.1"
}
```

**Screenshots**
![image](https://github.com/user-attachments/assets/ef43c587-f27f-47e0-82ef-bfe403eb4824)

**Temporary solution test**
Applied solution from https://github.com/wix/react-native-navigation/issues/7821#issuecomment-1865390682 and issue resolved.

Thanks a bunch @jtich!

<img width="467" alt="image" src="https://github.com/user-attachments/assets/46c3c791-1f03-4a82-8fa8-4f130d923af6">

**Comment by d4vidi** [comment]
We're planning to revisit this in the future, but it's going to take a while. **We could really use some help from the community with this one**, we don't have immediate capacity to address these kind of issues 🙏🏻

**Comment by badalsaibo** [comment]
`rnn-link` is still broken on Android even after applying the above patch

```
Linking MainApplication...
   Error: There was a problem extending NavigationApplication from your MainApplication file.
   Error: There was a problem extending NavigationReactNativeHost().
   SOLoader.init() is not called, skipping.
MainApplication.java was partially linked. Please check the information above and complete the missing steps manually:
   https://wix.github.io/react-native-navigation/docs/installing#3-update-mainapplicationjava
   MainActivity not found! Does the file exist in the correct folder?
   Please check the manual installation docs:
   https://wix.github.io/react-native-navigation/docs/installing#2-update-mainactivityjava
Linking root build.gradle...
   Adding RNNKotlinVersion extension variable
   Error:    Could not add kotlin plugin dependency
   Already specified minSdkVersion 21
Root build.gradle link partially succeeded. Please review the information above and complete the necessary steps manually by following the instructions on https://wix.github.io/react-native-navigation/docs/installing#1-update-androidbuildgradle
```

**Comment by gusilveiramp** [comment]
+1

**Comment by gusilveiramp** [comment]
To avoid directly modifying the file in the node_modules folder, I created a postinstall script based on [@jtich comment](https://github.com/wix/react-native-navigation/issues/7821#issuecomment-1865390682). This script automates the fix for Kotlin support in rnn-link:

1. Add postinstall to package.json:
```js
"scripts": {
  "postinstall": "node scripts/fix-path.js"
}
```

2. Create the fix-path.js file:
```js
/**
 * Fixes an issue with the react-native-navigation's rnn-link command.
 * Reference: https://github.com/wix/react-native-navigation/issues/7821#issuecomment-1865390682
 */
const fs = require('fs');
const path = require('path');

// Path to the path.js file
const filePath = path.join(__dirname, '..', 'node_modules', 'react-native-navigation', 'autolink', 'postlink', 'path.js');

// Replaces the code to support .kt files
fs.readFile(filePath, 'utf8', function (err, data) {
  if (err) {
    return console.log(err);
  }
  const result = data.replace(
    'var mainApplicationJava = glob.sync(\'**/MainApplication.java\', ignoreFolders)[0];',
    'var mainApplicationJava = glob.sync(\'**/MainApplication.{java,kt}\', ignoreFolders)[0];'
  );

  fs.writeFile(filePath, result, 'utf8', function (err) {
    if (err) {return console.log(err);}
    console.log('Fix applied to path.js for Kotlin support.');
  });
});
```
3. Run the script:
```sh
yarn install  # or yarn postinstall
```

**Comment by gusilveiramp** [comment]
Even though ```npx rnn-link``` runs correctly after applying the postinstall script, the Android build still fails with the following error:

```
Task :react-native-navigation:compileReactNative71DebugKotlin
```

**Comment by rendomnet** [comment]
> The issue is that the following [line in path.js](https://github.com/wix/react-native-navigation/blob/6e7e8f61d4826b79a898a10adc49c72eb1a98b02/autolink/postlink/path.js#L8) assumes that `mainApplication` has the `java` extension, however it's now a kotlin file, which is why `mainApplicationJava` is undefined.
> 
> I was able to get around this issue by changing this line...
> 
> ```js
> var mainApplicationJava = glob.sync('**/MainApplication.java', ignoreFolders)[0];
> ```
> 
> to the following:
> 
> ```js
> var mainApplicationJava = glob.sync('**/MainApplication.{java,kt}', ignoreFolders)[0];
> ```
> 
> This way the glob.sync func matches both file extensions.

Why this is not merged?

**Comment by retyui** [comment]
@rendomnet Because it useless and helps to skip error message, without applying a Kotlin liker code

**Comment by retyui** [comment]
You can use a tmp. ver with a fixed `rnn-link` command. (after linking return to regular RRN version) 
```sh
yarn add react-native-navigation@https://github.com/retyui/react-native-navigation.git#feat/retyui/add-kotlin-autolinker
npx rnn-link
yarn add react-native-navigation # or use our own version
```

**Comment by rendomnet** [comment]
@retyui Coul you confirm that is it working with react-native 0.76.3? Becuase in my case it is not.

**Comment by rendomnet** [comment]
> Even though `npx rnn-link` runs correctly after applying the postinstall script, the Android build still fails with the following error:
> 
> ```
> Task :react-native-navigation:compileReactNative71DebugKotlin
> ```

Did you found a solution?

**Comment by soyaaroncervantes** [comment]
[@brifiction solution](https://github.com/wix/react-native-navigation/issues/7821#issuecomment-2276987954), worked for me.

I'm using Re.pack with RNN@0.78.2. 

What I fell it's worst, the documentation is not updated, and at least, it should warning about this issue.

Because Swift example is in ObjectiveC and code in Swift 💔
